# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "verify"
  lane :verify do |options|
    pod_lib_lint(
      allow_warnings: true,
      use_libraries: true
    )
  end
end

platform :ios do
  desc "deploy"
  lane :deploy do
    pod_lib_lint(
      allow_warnings: true,
      use_libraries: true
    )
    version = version_bump_podspec(path: "SwifterExtensions.podspec")
    git_commit(path: "./*.podspec", message: "Bumped to version #{version}")
    add_git_tag(tag: version)
    push_to_git_remote(remote_branch: "master", force: false, tags: true)
    # changelog = changelog_from_git_commits
    # sh("git fetch --tags")
    pod_push(
      path: "SwifterExtensions.podspec",
      allow_warnings: true, 
      use_libraries: true,
      # 跳过验证 pod 是否可以导入
      # skip_import_validation: true,
      verbose: true
    )
  end
end
